/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package edu.utexas.cs345.jdblisp.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ALTER = 1;
  /** RegularExpression Id. */
  int COMMENT = 2;
  /** RegularExpression Id. */
  int CREATE = 3;
  /** RegularExpression Id. */
  int DROP = 4;
  /** RegularExpression Id. */
  int RENAME = 5;
  /** RegularExpression Id. */
  int ANALYZE = 6;
  /** RegularExpression Id. */
  int EXPLAIN = 7;
  /** RegularExpression Id. */
  int AUDIT = 8;
  /** RegularExpression Id. */
  int NOAUDIT = 9;
  /** RegularExpression Id. */
  int GRANT = 10;
  /** RegularExpression Id. */
  int REVOKE = 11;
  /** RegularExpression Id. */
  int SET = 12;
  /** RegularExpression Id. */
  int ROLE = 13;
  /** RegularExpression Id. */
  int SELECT = 14;
  /** RegularExpression Id. */
  int UPDATE = 15;
  /** RegularExpression Id. */
  int DELETE = 16;
  /** RegularExpression Id. */
  int INSERT = 17;
  /** RegularExpression Id. */
  int TRUNCATE = 18;
  /** RegularExpression Id. */
  int TRANSACTION = 19;
  /** RegularExpression Id. */
  int LOCK = 20;
  /** RegularExpression Id. */
  int DATABASE = 21;
  /** RegularExpression Id. */
  int TABLE = 22;
  /** RegularExpression Id. */
  int LPAREN = 29;
  /** RegularExpression Id. */
  int RPAREN = 30;
  /** RegularExpression Id. */
  int NIL = 31;
  /** RegularExpression Id. */
  int QUOTE = 32;
  /** RegularExpression Id. */
  int FUNCTION = 33;
  /** RegularExpression Id. */
  int KEYWORD = 34;
  /** RegularExpression Id. */
  int COMMA = 35;
  /** RegularExpression Id. */
  int NUMB = 36;
  /** RegularExpression Id. */
  int STRG = 37;
  /** RegularExpression Id. */
  int SYMB = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"alter\"",
    "\"comment\"",
    "\"create\"",
    "\"drop\"",
    "\"rename\"",
    "\"analyze\"",
    "\"explain\"",
    "\"audit\"",
    "\"noaudit\"",
    "\"grant\"",
    "\"revoke\"",
    "\"set\"",
    "\"role\"",
    "\"select\"",
    "\"update\"",
    "\"delete\"",
    "\"insert\"",
    "\"truncate\"",
    "\"transaction\"",
    "\"lock\"",
    "\"database\"",
    "\"table\"",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\n\\r\"",
    "<token of kind 28>",
    "\"(\"",
    "\")\"",
    "<NIL>",
    "\"\\\'\"",
    "\"#\\\'\"",
    "\":\"",
    "<COMMA>",
    "<NUMB>",
    "<STRG>",
    "<SYMB>",
  };

}
